### ISSUE TITLE
Supercool :) Limitations on the prompt length?

### ISSUE THREAD

**Issue by rjalexa** [aborroy/llama2-docker-multiarch#1]
First of all thanks a lot for your work. Very much appreciated.

A suggestion please.

I would like to pass it a newspaper article asking to find entities in it. Text is usually 3000-4000 chars. Think this would work?

How would you handle texts with quotes and other crap :) ? 

Take care.

**Comment by aborroy** [comment]
Passing the input as a file is an option for you?

https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md#input-prompts

Not sure if this option (`--file`) is the one you need.

**Comment by rjalexa** [comment]
Will try thanks. In the future I would like to submit a text to the LLM from my python code. Any suggestion on the best way to do it?

**Comment by aborroy** [comment]
Did you try this project?
https://github.com/maxi-w/llama2-chat-interface
